variables:
  PROJECT_NAME: "nestjs-builder-api"
  DOCKER_REPO: "chenawy-docker.pkg.coding.net/jcjy/docker"

stages:
  - build-api

build:
  stage: build-api
  tags:
    - jcjy
  script:
    - docker build -t dummy/${PROJECT_NAME}:$CI_COMMIT_REF_NAME .
    - docker tag dummy/${PROJECT_NAME}:$CI_COMMIT_REF_NAME ${DOCKER_REPO}/${PROJECT_NAME}:$CI_COMMIT_REF_NAME
    - docker push ${DOCKER_REPO}/${PROJECT_NAME}:$CI_COMMIT_REF_NAME
    - curl --data-urlencode "content=${PROJECT_NAME} build done" https://h.tltr.top/g/Tdi7Fjg
