version: "3.5"

services:
  api:
    image: iyjian/nestjs-builder-api  
    # image: iyjian/api
    # build:
    #   context: ./api    
    restart: always
    environment:
      - PORT=3000    
    env_file:
      - ./api/.env
  ui:
    image: iyjian/nestjs-builder-ui
    # image: iyjian/devfront
    # build:
    #   context: ./ui
    restart: always
    env_file:
      - ./api/.env
    ports:
      - 53001:80
