#!/bin/bash

docker pull iyjian-docker.pkg.coding.net/jcjy/docker/nestjs-builder-api:dev && \
docker pull iyjian-docker.pkg.coding.net/jcjy/docker/nestjs-builder-ui:dev && \
docker-compose down && \
docker-compose up -d
