#!/bin/bash

docker pull chenawy-docker.pkg.coding.net/jcjy/docker/nestjs-builder-api && \
docker pull chenawy-docker.pkg.coding.net/jcjy/docker/nestjs-builder-ui && \
docker-compose down && \
docker-compose up -d
