export const EnumType = {
  // 采购类型
  PURCHASE_TYPE: 'PURCHASE_TYPE',

  //1.WC的枚举值
  EDUCATION_LEVEL: 'EDUCATION_LEVEL',
  // 计量单位
  ITEM_MEASURE: 'ITEM_MEASURE',
  // 考评模板类型
  CREW_ASSESSMENT_TYPE: 'CREW_ASSESSMENT_TYPE',
  // 职位类型
  POSITION_TYPE: 'POSITION_TYPE',
  // 船员职位申请状态
  CREW_JOB_APPLY_STATUS: 'CREW_JOB_APPLY_STATUS',
  // 船员面试状态
  CREW_INTERVIEW_STATUS: 'CREW_INTERVIEW_STATUS',
  // 船员合同类型
  CREW_CONTRACT_TYPE: 'CREW_CONTRACT_TYPE',
  // 船员职能等级
  CREW_JOB_LEVEL: 'CREW_JOB_LEVEL',
  // 船员课程类型
  CREW_COURSE_TYPE: 'CREW_COURSE_TYPE',
  // 船员培训的状态
  CREW_TRAINING_STATUS: 'CREW_TRAINING_STATUS',
  // 船员课程状态
  CREW_COURSE_STATUS: 'CREW_COURSE_STATUS',
  // 船员照片类型 现在有 个人照片 身份证 护照 海员证 健康证 服务簿 其他
  CREW_PICTURE_TYPE: 'CREW_PICTURE_TYPE',
  // 船员证书类型
  CERTIFICATE_TYPE: 'CERTIFICATE_TYPE',
  // 婚姻状态
  MARRIED_STATUS: 'MARRIED_STATUS',
  // 血型
  BLOOD_TYPE: 'BLOOD_TYPE',
  // 肤色
  SKIN_COLOR_TYPE: 'SKIN_COLOR_TYPE',
  // 演习类型
  CREW_EXERCISE_TYPE: 'CREW_EXERCISE_TYPE',
  // 演习状态
  CREW_EXERCISE_STATUS: 'CREW_EXERCISE_STATUS',
  // 币种，用在计算工资的地方
  CURRENCY_TYPE: 'CURRENCY_TYPE',
  // 招聘状态
  RECRUITMENT_STATUS: 'RECRUITMENT_STATUS',
  // 和船员的联络方式
  CREW_TOUCH_WAY: 'CREW_TOUCH_WAY',
  // 设备类型
  EQUIPMENT_TYPE: 'EQUIPMENT_TYPE',
  // 船证书类型
  CRUISE_CERTIFICATE_TYPE: 'CRUISE_CERTIFICATE_TYPE',
  // 船上文件类型
  CRUISE_DOCUMENT_TYPE: 'CRUISE_DOCUMENT_TYPE',
  // 船舶类型
  CRUISE_TYPE: 'CRUISE_TYPE',
  // 疫苗类型(1必须是新冠疫苗)
  VACCINATION_TYPE: 'VACCINATION_TYPE',

  // 2.xiaoc的枚举值

  //文件大类别
  DOCUMENTS_CATEGORY: 'DOCUMENTS_CATEGORY',
  //文件分类
  DOCUMENTS_SUBCATEGORY: 'DOCUMENTS_SUBCATEGORY',
  //主办部门
  DOCUMENTS_DEPARTMENT: 'DOCUMENTS_DEPARTMENT',
  //发布机构
  DOCUMENTS_AGENCY: 'DOCUMENTS_AGENCY',

  //申请类型
  APPLY_TYPE: 'APPLY_TYPE',
  //记录状态
  APPLY_STATE: 'APPLY_STATE',
  //执行状态
  EXECUTION_STATE: 'EXECUTION_STATE',
  //审批状态
  EXECUTION_SUB_STATE: 'EXECUTION_SUB_STATE',
  //检查分类
  EXAMINATION_CATEGORY: 'EXAMINATION_CATEGORY',
  //检查状态
  EXAMINATION_STATE: 'EXAMINATION_STATE',
  //操作类型
  ACCIDENT_RSUB_TYPE: 'ACCIDENT_RSUB_TYPE',
  //风险因素
  ACCIDENT_RSUB_RISKFACTOR: 'ACCIDENT_RSUB_RISKFACTOR',
  //风险隐患发生的可能性
  ACCIDENT_RSUB_POSSIBILITY: 'ACCIDENT_RSUB_POSSIBILITY',
  //风险隐患发生的后果严重程度
  ACCIDENT_RSUB_AFTERMATH: 'ACCIDENT_RSUB_AFTERMATH',
  //风险隐患等级
  ACCIDENT_RSUB_LEVEL: 'ACCIDENT_RSUB_LEVEL',
  //货物类型
  GOODS_TYPE: 'GOODS_TYPE',
  //流程类型
  WORKFLOW_TYPE: 'WORKFLOW_TYPE',
  //流程设置步骤类型
  WORKFLOW_SUB_TYPE: 'WORKFLOW_SUB_TYPE',
  //基薪币种
  PAYROLL_CURRENCY: 'PAYROLL_CURRENCY',

  //发放状态
  PAYROLL_STATUS: 'PAYROLL_STATUS',
  //工单负责人
  WORKORDER_LEADER: 'WORKORDER_LEADER',
  //工单类型
  WORKORDER_TYPE: 'WORKORDER_TYPE',
  //工单紧急程度
  WORKORDER_URGENCY: 'WORKORDER_URGENCY',
  //工单状态
  WORKORDER_STATE: 'WORKORDER_STATE',
  //维修类型
  MAINTENANCE_TYPE: 'MAINTENANCE_TYPE',
  //维修紧急程度
  MAINTENANCE_URGENCY: 'MAINTENANCE_URGENCY',
  // 公告类型
  NOTICE_TYPE: 'NOTICE_TYPE',

  // 周期类型
  WORKORDER_PTYPE: 'WORKORDER_PTYPE',

  //审核意见
  MAINTENANCE_COMMENTS: 'MAINTENANCE_COMMENTS',
  //维修状态
  MAINTENANCE_STATUS: 'MAINTENANCE_STATUS',
}
